[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.9.3",
    "pandas==2.2.3",
    "sympy>=1.14.0",
]
